// GET SINGLE IMAGE FROM DATABASE
GET http://localhost:8080/api/images/:id

###
// POST A SINGLE IMAGE
POST http://localhost:8080/api/images
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="Hafling.png"
Content-Type: image/png

< ./Hafling.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
// DELETE A SINGLE IMAGE
DELETE http://localhost:8080/api/images