//GET ALL RECIPES
GET http://localhost:8080/api/recipes/

###

//GET ONE RECIPE
GET http://localhost:8080/api/recipes/5fe349bcef487237387d42e1

###

//GET RECIPE BY FREETEXT

//GET RECIPE BY DIFFICULTY

//GET RECIPE BY COOKINGTIME

//GET RECIPE BY AUTHOR

//POST RECIPE
POST http://localhost:8080/api/recipes/
Content-Type: application/json

{
    "title" : "SommarTacos",
    "preambleHTML" : "En fräsch taco med panerad torsk. Den sötstarka mangosalsan ger mycket fraschör. Var inte rädd för att dunka på en del med chilin, mangon och limedressingen tar ut en del styrka.",
    "imageURL" : "https://img.koket.se/standard-mega/fisktacos-med-guacamole-och-mangosalsa.jpg.webp",
    "portions" : 4,
    "cookingTime" : "10-20min",
    "difficulty" : "LÄTT",
    "ingredients" : [
        {
            "quantityFraction" : "8",
            "unit" : "st",
            "ingredient" : "Färdigpanerad Torsk"
        },
                {
            "quantityFraction" : "4",
            "unit" : "st",
            "ingredient" : "Tortillabröd"
        },
                {
            "quantityFraction" : "500",
            "unit" : "gr",
            "ingredient" : "Mango"
        },
                {
            "quantityFraction" : "2",
            "unit" : "st",
            "ingredient" : "Färsk Chili"
        },
                {
            "quantityFraction" : "3",
            "unit" : "dl",
            "ingredient" : "gräddfil eller havregojs"
        },
                {
            "quantityFraction" : "1",
            "unit" : "st",
            "ingredient" : "lime"
        }
    ],
    "cookingSteps" : [
        "Riv av skalet av limen och blanda ner det i gräddfilen. Ställ såsen i kylen. TIPS! Ju längre såsen får stå med limeskalen i, desto mer lime kommer såsen att smaka.",
        "Tärna mangon i centimeterstora bitar. Skiva chilin tunnt. Blanda ihop och låt götta sig en stund. Även Salsan mår ra av att stå i någon timme innan servering, men smakar fint även om den serveras direkt.",
        "Tillaga Torsken efter beskrivningen på paketet.",
        "Skiva torsken på hälften på längden. Ta fram ett tortilla-bröd. Lägg en eller två torskbitar på brödet. Häll på mangosalsa och klicka sedan på några klickar limesås.",
        "Vik din tortilla. Tadaaa~! Redo att avnjutas"
    ],
    "mdsaCategories" : [
        "taco",
        "fisk",
        "fredagsmys"
    ],
    "author" : "Lee",
    "isShared" : false
}

###
//PUT RECIPE
PUT http://localhost:8080/api/recipes/5fe3473b058baa3cac7d8689
Content-Type: application/json

{
    "title" : "Exotiska Tacos",
    "preambleHTML" : "Smakar som sådana man äter på Jamaica",
    "imageURL" : "https://img.koket.se/standard-mega/fisktacos-med-guacamole-och-mangosalsa.jpg.webp",
    "portions" : 4,
    "cookingTime" : "15min",
    "difficulty" : "SVÅR",
    "ingredients" : [
        {
            "quantityFraction" : "8",
            "unit" : "st",
            "ingredient" : "Tonfiskar"
        },
                {
            "quantityFraction" : "4",
            "unit" : "st",
            "ingredient" : "Tortillabröd"
        },
                {
            "quantityFraction" : "500",
            "unit" : "gr",
            "ingredient" : "Mango"
        },
                {
            "quantityFraction" : "2",
            "unit" : "st",
            "ingredient" : "Färsk Chili"
        },
                {
            "quantityFraction" : "3",
            "unit" : "dl",
            "ingredient" : "gräddfil eller havregojs"
        },
                {
            "quantityFraction" : "1",
            "unit" : "st",
            "ingredient" : "lime"
        }
    ],
    "cookingSteps" : [
        "Riv av skalet av limen och blanda ner det i gräddfilen. Ställ såsen i kylen. TIPS! Ju längre såsen får stå med limeskalen i, desto mer lime kommer såsen att smaka.",
        "Tärna mangon i centimeterstora bitar. Skiva chilin tunnt. Blanda ihop och låt götta sig en stund. Även Salsan mår ra av att stå i någon timme innan servering, men smakar fint även om den serveras direkt.",
        "Tillaga Torsken efter beskrivningen på paketet.",
        "Skiva torsken på hälften på längden. Ta fram ett tortilla-bröd. Lägg en eller två torskbitar på brödet. Häll på mangosalsa och klicka sedan på några klickar limesås.",
        "Vik din tortilla. Tadaaa~! Redo att avnjutas"
    ],
    "mdsaCategories" : [
        "taco",
        "fisk",
        "fredagsmys"
    ],
    "author" : "Lee",
    "isShared" : false
}

###

//DELETE RECIPE
DELETE http://localhost:8080/api/recipes/5fe3484a33aeeb1cc01876f5