//GET ALL RECIPES
GET http://localhost:8080/api/recipes/

###

//GET RECIPE BY ID
GET http://localhost:8080/api/recipes/6005daeb83df2937ec206ee6

###

//GET RECIPE BY FREETEXT

//GET RECIPE BY Author
GET http://localhost:8080/api/recipes/author/Starstoft

###

//GET RECIPE BY COOKINGTIME

//POST RECIPE
POST http://localhost:8080/api/recipes/
Content-Type: application/json

{
    "title" : "Havregrynsgröt extra allt",
    "preambleHTML" : "En bra morgon startar med havregrynsgrött, men den bästa startar med havregrynsgröt EXTRA ALLT. Nötter, frön och frukt kan ampa vilken gröt som helst. ",
    "imageURL" : "https://img.koket.se/standard-mega/fisktacos-med-guacamole-och-mangosalsa.jpg.webp",
    "portions" : 1,
    "cookingTime" : "5-10min",
    "difficulty" : "JÄTTELÄTT",
    "ingredients" : [
        {
            "quantityFraction" : "1",
            "unit" : "dl",
            "ingredient" : "havregryn"
        },
                {
            "quantityFraction" : "2,5",
            "unit" : "dl",
            "ingredient" : "vatten"
        },
                {
            "quantityFraction" : "1",
            "unit" : "msk",
            "ingredient" : "frön"
        },
                {
            "quantityFraction" : "1",
            "unit" : "msk",
            "ingredient" : "Nötter"
        },
                {
            "quantityFraction" : "1",
            "unit" : "st",
            "ingredient" : "banan"
        },
                {
            "quantityFraction" : "0.5",
            "unit" : "tsk",
            "ingredient" : "kardemumma"
        }
    ],
    "cookingSteps" : [
        "mät upp torra ingredienser",
        "finhacka bananen och blanda i",
        "häll på vätska",
        "blanda och smaka av med salt tills vattnet smakar lagom saltigt för dig",
        "kör på 2,5 min i micron",
        "avnjut med valfri mjölksort och kanske lite sirap eller honung?"
    ],
    "mdsaCategories" : [
        "frukost",
        "mellanmål",
        "gröt"
    ],
    "author" : "Starstoft",
    "isShared" : false
}

###

//PUT RECIPE
PUT http://localhost:8080/api/recipes/5fe3473b058baa3cac7d8689
Content-Type: application/json

{
    "title" : "Exotiska Tacos",
    "preambleHTML" : "Smakar som sådana man äter på Jamaica",
    "imageURL" : "https://img.koket.se/standard-mega/fisktacos-med-guacamole-och-mangosalsa.jpg.webp",
    "portions" : 4,
    "cookingTime" : "15min",
    "difficulty" : "SVÅR",
    "ingredients" : [
        {
            "quantityFraction" : "8",
            "unit" : "st",
            "ingredient" : "Tonfiskar"
        },
                {
            "quantityFraction" : "4",
            "unit" : "st",
            "ingredient" : "Tortillabröd"
        },
                {
            "quantityFraction" : "500",
            "unit" : "gr",
            "ingredient" : "Mango"
        },
                {
            "quantityFraction" : "2",
            "unit" : "st",
            "ingredient" : "Färsk Chili"
        },
                {
            "quantityFraction" : "3",
            "unit" : "dl",
            "ingredient" : "gräddfil eller havregojs"
        },
                {
            "quantityFraction" : "1",
            "unit" : "st",
            "ingredient" : "lime"
        }
    ],
    "cookingSteps" : [
        "Riv av skalet av limen och blanda ner det i gräddfilen. Ställ såsen i kylen. TIPS! Ju längre såsen får stå med limeskalen i, desto mer lime kommer såsen att smaka.",
        "Tärna mangon i centimeterstora bitar. Skiva chilin tunnt. Blanda ihop och låt götta sig en stund. Även Salsan mår ra av att stå i någon timme innan servering, men smakar fint även om den serveras direkt.",
        "Tillaga Torsken efter beskrivningen på paketet.",
        "Skiva torsken på hälften på längden. Ta fram ett tortilla-bröd. Lägg en eller två torskbitar på brödet. Häll på mangosalsa och klicka sedan på några klickar limesås.",
        "Vik din tortilla. Tadaaa~! Redo att avnjutas"
    ],
    "mdsaCategories" : [
        "taco",
        "fisk",
        "fredagsmys"
    ],
    "author" : "Lee",
    "isShared" : false
}

###

//PATCH
PATCH http://localhost:8080/api/recipes/6005daeb83df2937ec206ee6
Content-Type: application/json

{
    "isShared" : true
}

###

//DELETE RECIPE
DELETE http://localhost:8080/api/recipes/5fe3484a33aeeb1cc01876f5