//GET ALL RECIPES
GET http://localhost:8080/api/recipes

//GET ONE RECIPE

//GET RECIPE BY FREETEXT

//GET RECIPE BY DIFFICULTY

//GET RECIPE BY COOKINGTIME

//GET RECIPE BY AUTHOR

//POST RECIPE

//PUT RECIPE

//DELETE RECIPE