GET http://localhost:8080/api/users/all

###
GET http://localhost:8080/api/users/

###
POST http://localhost:8080/api/users/
Content-Type: application/json

{
    "username" : "Ninja",
    "password" : "secret",
    "firstName" : "Annely",
    "lastName" : "Back",
    "userInfo" : "Jag gillar mat ännu mer",
    "recipeBook" : [],
    "externalRecipes" : []
}

###
PUT http://localhost:8080/api/users/6009769f9665db27906615ab
Content-Type: application/json

{
    "username" : "Ninja",
    "password" : "secret",
    "firstName" : "Ninja",
    "lastName" : "Bäck",
    "image" : "6009769d9665db27906615a9",
    "userInfo" : "Jag är starstofts hund",
    "recipeBook" : ["600820d47e4368413ca21fdf"],
    "imageURL": "http://localhost:8080/api/images/6009769d9665db27906615a9"
}

###
DELETE http://localhost:8080/api/users/:id

###
POST http://localhost:8080/api/users/session/login/
Content-Type: application/json

{
    "username" : "Ninja",
    "password" : "secret"
}

###

//TODO Fixa denna?
DELETE http://localhost:8080/api/users/session/logout/