GET https://receptmingel.herokuapp.com/api/users/all

###
GET http://localhost:8080/api/users/

###
GET https://receptmingel.herokuapp.com/api/users/600806e24c55ab2c8c310f77

###
GET https://receptmingel.herokuapp.com/api/users/recipebook/600806e24c55ab2c8c310f77

###
POST https://receptmingel.herokuapp.com/api/users/
Content-Type: application/json

{
    "username" : "Skitunge",
    "password" : "secret",
    "firstName" : "Annely",
    "lastName" : "Back",
    "userInfo" : "Jag gillar mat ännu mer",
    "image" : '',
    "recipeBook" : [],
    "externalRecipes" : []
}

###
PATCH https://receptmingel.herokuapp.com/api/users/600806e24c55ab2c8c310f77
Content-Type: application/json

{
    "recipeBook" : ["600843ee1a7f0b38b4973e3b", "600daa2e1097d20015451066", "600820d47e4368413ca21fdf"]
}

###
DELETE http://localhost:8080/api/users/:id

###
POST https://receptmingel.herokuapp.com/api/users/session/login
Content-Type: application/json

{
    "username" : "BangBang",
    "password" : "secret"
}

###

//TODO Fixa denna?
DELETE http://localhost:8080/api/users/session/logout/